name = "tutor-leochoi-info"
type = "webpack"
account_id = "0ded48be03f18b53d897f1e3e814570f"
workers_dev = true

[site]
bucket = "./www"
entry-point = "workers-site"

[env.production]
zone_id = "766d35169a0ca1a295eb47b2b529c021"
route = "tutor.leochoi.info/*"
